######################################################################
#
# Check dist
#
# Validates that the dist directory contents match the compiled
# and minimized source code. Because this directory is the code
# that will be executed by the action, it's important that it always
# matches the source code.
#
######################################################################

name: Check dist

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  check-dist:
    name: Check distribution
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Setup Yarn
        run: corepack enable && yarn set version berry
        env:
          COREPACK_ENABLE_DOWNLOAD_PROMPT: 0

      - name: Setup Node.js 20.x
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af
        with:
          node-version: 20.x
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: Rebuild the dist directory
        run: yarn run build

      - name: Compare the expected and actual dist directories
        id: diff
        run: "LINE_DIFF=$(git diff --ignore-space-at-eol --ignore-all-space ./dist | wc -l)\nif [ \"$LINE_DIFF\" -gt \"0\" ]; then\n  echo \"Detected uncommitted changes after the build ($LINE_DIFF). See the status below:\"\n  git diff --ignore-space-at-eol --ignore-all-space \n  exit 1\nfi\n"
      # If inners of the dist directory were different than expected,
      # upload the generated code as an artifact for comparison
      - name: Upload artifact
        if: ${{failure() && steps.diff.conclusion == 'failure'}}
        uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b
        with:
          name: dist
          path: ./dist
